-- 1. From the following table, write a SQL query to select all the salespeople.
--  Return salesman_id, name, city, commission with the percent sign (%).

SELECT * , "%"  FROM SALESMAN;

-- 2. From the following table, write a SQL query to find the number of orders booked for each day. 
-- Return the result in a format like "For 2001-10-10 there are 15 orders".". 

SELECT "FOR" , ORD_DATE , "THERE ARE " , COUNT(ORD_NO) , "ORDERS "
FROM ORDERS
GROUP BY ORD_DATE;

-- 3. From the following table, write a SQL query to find all the orders. 
-- Sort the result-set in ascending order by ord_no. Return all fields.

SELECT * FROM ORDERS
ORDER BY ORD_NO;

-- 4. From the following table, write a SQL query to find all the orders. 
-- Sort the result-set in descending order by ord_date. Return all fields. 

SELECT * FROM ORDERS
ORDER BY ORD_NO DESC;

-- 5. From the following table, write a SQL query to find all the orders. 
-- Sort the result-set in descending order by ord_date and purch_amt. Return all fields.  

SELECT * FROM ORDERS
ORDER BY ORD_DATE DESC , purch_amt DESC;

-- 6. From the following table, write a SQL query to find all the customers. 
-- Sort the result-set by customer_id. Return cust_name, city, grade.

SELECT cust_name,city , cust_name FROM customers
ORDER BY customer_id;

-- 7. From the following table, write a SQL query that calculates the maximum purchase 
-- amount generated by each salesperson for each order date. 
-- Sort the result-set by salesperson id and order date in ascending order. 
-- Return salesperson id, order date and maximum purchase amount. 

SELECT SALESMAN_ID , ORD_DATE , MAX(PURCH_AMT) AS MAX
FROM ORDERS
GROUP BY SALESMAN_ID , ORD_DATE
ORDER BY SALESMAN_ID , ORD_DATE;

-- 8. From the following table, write a SQL query to find all the customers. 
-- Sort the result-set in descending order on 3rd field. Return customer name, city and grade.  

SELECT cust_name , city , grade
FROM customers
ORDER BY 3 DESC;

-- 9. From the following table, write a SQL query that counts the unique orders and the highest 
-- purchase amount for each customer. 
-- Sort the result-set in descending order on 2nd field. 
-- Return customer ID, number of distinct orders and highest purchase amount by each customer. 

SELECT customer_id , COUNT(distinct ORD_NO) , MAX( PURCH_AMT)
FROM ORDERS 
GROUP BY customer_id
ORDER BY 2 DESC;

-- 10. From the following table, write a SQL query to calculate the summation of purchase amount,
--  total commission (15% for all salespeople) by each order date. 
--  Sort the result-set on order date. Return order date, summation of purchase amount and commission.

SELECT ORD_DATE , SUM(PURCH_AMT) , SUM(PURCH_AMT) * 0.15 AS 'TOTAL commission'
FROM ORDERS
GROUP BY ORD_DATE
ORDER BY ORD_DATE;

-- ANOTHER WAY : 
SELECT ORD_DATE , SUM(PURCH_AMT) , SUM(PURCH_AMT * 16/ 100) AS 'TOTAL COMMISSION'
FROM ORDERS
GROUP BY ORD_DATE
ORDER BY ORD_DATE;